Wunderman\EpreventionBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: titre
    properties:
        titre:
            - NotBlank: ~
            - Type: string
